from .models import Question
from typing import Protocol

class QuestionRepo(Protocol):
    # QuestionRepoインターフェースを定義
    # Javaのインターフェースのような感じ
    def add(self, q: Question) -> Question: ...
    def update(self, q: Question) -> Question: ...
    def delete(self, qid: int) -> None: ...
    def get(self, qid: int) -> Question | None: ...